# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1030, 748)
                MainWindow.setStyleSheet("color: black;\n" + "font: 75 13pt \"Yu Gothic UI\";")
                MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.additems = QtWidgets.QTabWidget(self.centralwidget)
                self.additems.setGeometry(QtCore.QRect(40, 60, 951, 631))
                self.additems.setStyleSheet("color: black;\n" + "font: 75 13pt \"MS Shell Dlg 2\";")
                self.additems.setObjectName("additems")
                self.tab = QtWidgets.QWidget()
                self.tab.setObjectName("tab")
                self.firstName = QtWidgets.QTextEdit(self.tab)
                self.firstName.setGeometry(QtCore.QRect(290, 70, 241, 31))
                self.firstName.setObjectName("firstName")
                self.label_2 = QtWidgets.QLabel(self.tab)
                self.label_2.setGeometry(QtCore.QRect(120, 130, 81, 16))
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.tab)
                self.label_3.setGeometry(QtCore.QRect(120, 190, 81, 16))
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.tab)
                self.label_4.setGeometry(QtCore.QRect(120, 240, 81, 16))
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.tab)
                self.label_5.setGeometry(QtCore.QRect(120, 290, 81, 16))
                self.label_5.setObjectName("label_5")
                self.cityName = QtWidgets.QTextEdit(self.tab)
                self.cityName.setGeometry(QtCore.QRect(290, 180, 241, 31))
                self.cityName.setObjectName("cityName")
                self.lastName = QtWidgets.QTextEdit(self.tab)
                self.lastName.setGeometry(QtCore.QRect(290, 120, 241, 31))
                self.lastName.setObjectName("lastName")
                self.addButton = QtWidgets.QPushButton(self.tab)
                self.addButton.setGeometry(QtCore.QRect(220, 340, 161, 51))
                self.addButton.setStyleSheet("background: blue;\n"
"color: white;\n"
"font: 75 14pt \"Arial\";\n"
"border: none;")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("../../../../Downloads/Logo-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.addButton.setIcon(icon)
                self.addButton.setCheckable(True)
                self.addButton.setDefault(False)
                self.addButton.setObjectName("addButton")
                self.countryName = QtWidgets.QTextEdit(self.tab)
                self.countryName.setGeometry(QtCore.QRect(290, 230, 241, 31))
                self.countryName.setObjectName("countryName")
                self.stateName = QtWidgets.QComboBox(self.tab)
                self.stateName.setGeometry(QtCore.QRect(290, 281, 241, 31))
                self.stateName.setCurrentText("")
                self.stateName.setObjectName("stateName")
                self.label = QtWidgets.QLabel(self.tab)
                self.label.setGeometry(QtCore.QRect(120, 80, 81, 16))
                self.label.setObjectName("label")
                self.additems.addTab(self.tab, "")
                self.tab_2 = QtWidgets.QWidget()
                self.tab_2.setObjectName("tab_2")
                self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
                self.tableWidget.setGeometry(QtCore.QRect(0, 60, 941, 471))
                self.tableWidget.setMinimumSize(QtCore.QSize(851, 0))
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(5)
                self.tableWidget.setRowCount(0)
                item = QtWidgets.QTableWidgetItem()
                icon = QtGui.QIcon.fromTheme("item")
                item.setIcon(icon)
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(4, item)
                self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
                self.doubleSpinBox.setGeometry(QtCore.QRect(650, 0, 81, 41))
                self.doubleSpinBox.setDecimals(0)
                self.doubleSpinBox.setMaximum(1000000000000.0)
                self.doubleSpinBox.setProperty("value", 0.0)
                self.doubleSpinBox.setObjectName("doubleSpinBox")
                self.pushButton = QtWidgets.QPushButton(self.tab_2)
                self.pushButton.setGeometry(QtCore.QRect(740, 0, 201, 41))
                self.pushButton.setObjectName("pushButton")
                self.label_6 = QtWidgets.QLabel(self.tab_2)
                self.label_6.setGeometry(QtCore.QRect(10, 0, 631, 41))
                self.label_6.setObjectName("label_6")
                self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
                self.pushButton_2.setGeometry(QtCore.QRect(780, 540, 161, 41))
                self.pushButton_2.setObjectName("pushButton_2")
                self.additems.addTab(self.tab_2, "")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 36))
                self.menubar.setObjectName("menubar")
                self.menuVroomhive = QtWidgets.QMenu(self.menubar)
                self.menuVroomhive.setObjectName("menuVroomhive")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
                self.menubar.addAction(self.menuVroomhive.menuAction())

                self.retranslateUi(MainWindow)
                self.additems.setCurrentIndex(1)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.firstName.setPlaceholderText(_translate("MainWindow", "Enter your name"))
                self.label_2.setText(_translate("MainWindow", "Last Name"))
                self.label_3.setText(_translate("MainWindow", "City"))
                self.label_4.setText(_translate("MainWindow", "Country"))
                self.label_5.setText(_translate("MainWindow", "State"))
                self.cityName.setPlaceholderText(_translate("MainWindow", "Enter your city"))
                self.lastName.setPlaceholderText(_translate("MainWindow", "Enter your last name"))
                self.addButton.setText(_translate("MainWindow", "Add"))
                self.addButton.setShortcut(_translate("MainWindow", "Ctrl+A"))
                self.countryName.setPlaceholderText(_translate("MainWindow", "Enter your country"))
                self.label.setText(_translate("MainWindow", "First Name"))
                self.additems.setTabText(self.additems.indexOf(self.tab), _translate("MainWindow", "Add items"))
                item = self.tableWidget.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "ID"))
                item = self.tableWidget.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "First Name"))
                item = self.tableWidget.horizontalHeaderItem(2)
                item.setText(_translate("MainWindow", "Last Name"))
                item = self.tableWidget.horizontalHeaderItem(3)
                item.setText(_translate("MainWindow", "City"))
                item = self.tableWidget.horizontalHeaderItem(4)
                item.setText(_translate("MainWindow", "Country"))
                self.pushButton.setText(_translate("MainWindow", "Search"))
                self.label_6.setText(_translate("MainWindow", "Search For Item In the Database"))
                self.pushButton_2.setText(_translate("MainWindow", "GetData"))
                self.additems.setTabText(self.additems.indexOf(self.tab_2), _translate("MainWindow", "Items"))
                self.menuVroomhive.setTitle(_translate("MainWindow", "Vroomhive"))

                self.addButton.clicked.connect(self.showData)

        def showData(self):
                db = sqlite3.connect("vroomware.db")
                cursor = db.cursor()


                # query = '''CREATE TABLE "contacts" (
                #         "ID"	INTEGER NOT NULL UNIQUE,
                #         "first_name"	TEXT NOT NULL,
                #         "last_name"	TEXT NOT NULL,
                #         "city"	TEXT NOT NULL,
                #         "country"	INTEGER NOT NULL,
                #         PRIMARY KEY("ID" AUTOINCREMENT)
                # );'''
                query = ''' SELECT * FROM 'contacts' '''

                results = cursor.execute(query)
                self.tableWidget.setRowCount(0)

                print(results)
                cursor.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
